### ISSUE TITLE
How to upgrade from Li-f-e-20.04.2 to Li-f-e-22.04

### ISSUE THREAD

**Issue by vladtemoc** [cyberorg/Life#1]
So far I have not found a way to update to the new version, I would like to know if it is possible from a command line. I hope you can help me.

**Comment by cyberorg** [comment]
As Life is based on Ubuntu, you can follow instructions such as these: https://itsfoss.com/upgrade-ubuntu-version/

If you are comfortable editing files in /etc/apt/sources.* files then you can change distro name in those files and run apt commands to upgrade.

You can always install new version over previous install if have / and /home in separate partitions.
